<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>The Super Game Site</title>
  <link rel="stylesheet" href="/src/web/css/style.css">
  <link rel="stylesheet" href="/src/web/css/normalize.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <script src="/src/web/js/game.js"></script>
</head>
<body>
    <div class="court">
        <div class="empty-dices"><?= $diceCount ?> Empty dice's</div>
        <div class="dices">
            <?php
                while ($diceCount > 0) {
                    print_r("<div class=\"dice dice-$diceCount\"></div>");
                    $diceCount--;
                }
            ?>
        </div>
        <div class="dice-score dice-score-<?= $diceScore; ?>"></div>
        <div class="step-score"><?= $stepScore; ?></div>
        <div class="total-score"><?= $totalScore; ?></div>
        <div id="pimpa" class="<?= $position ?>"></div>
        <button id="start-game">Start</button>
        <button id="reset-game">Reset</button>
    </div>
</body>
</html>
